### ISSUE TITLE
Segment置顶的时候，要网上拉倒头部的时候，没有流畅一次性的下拉，而是Segment依然黏着。

### ISSUE THREAD

**Issue by linsaw** [Liqiankun/DLWeiboProfileController#1]
Segment置顶的时候，要网上拉倒头部的时候，没有流畅一次性的下拉，而是Segment依然黏着，必须在拉动一次，这一点体验式可能不太好，能否完善下。

**Comment by Liqiankun** [comment]
是的，这个问题我也发现了，还没有好的解决方案！这两天我看一下，你也可以提建议🙂

**Comment by linsaw** [comment]
今天认真研究了下，你这个似乎主要吧
        if (!self.isTouch) {//当手指离开了，也不允许显示主控制器，这里可以根据实际需求做处理
            return;
        }
注释掉，就不会粘着了

**Comment by Liqiankun** [comment]
@luffySaw 我去看一下！这个去掉会不会产生其他问题！
