### ISSUE TITLE
代码中的baseVC用的是TableViewControllView，这就局限住了某些实现，比如我要搞collectionview。

### ISSUE THREAD

**Issue by linsaw** [Liqiankun/DLWeiboProfileController#2]
代码中的baseVC用的是TableViewControllView，这就局限住了某些实现，比如我要搞collectionview。有个分页要展示相册瀑布流功能，这就有局限性了，目前正在想着能不能直接基于普通的ViewController来处理。不知道大佬有啥建议？

**Comment by Liqiankun** [comment]
你先试试！哈哈。

**Comment by Liqiankun** [comment]
@luffySaw 这个你可以直接改成collectionView

**Comment by linsaw** [comment]
直接改成collectionView是什么意思？没理解，请指教

**Comment by Liqiankun** [comment]
@luffySaw `@interface BaseTableViewController : UITableViewController`改成`@interface BaseTableViewController : UICollectionViewController`

**Comment by linsaw** [comment]
我的意思是有的列表用UITableView，有的列表用UICollectionView，并不是统一UITableViewController或者UICollectionViewController
